COUNTRY_CODES = {  
    'SK': 'Slovakia',  
    'US': 'United States',  
    'CA': 'Canada',  
    'SE': 'Sweden',  
    'CZ': 'Czech Republic',  
    'AT': 'Austria',  
    'RU': 'Russia',  
    'FI': 'Finland',  
    'CH': 'Switzerland',  
    'DE': 'Germany',  
    'LV': 'Latvia',  
    'PL': 'Poland',  
    'BY': 'Belarus',  
    'GB': 'United Kingdom',  
    'KZ': 'Kazakhstan',  
    'NO': 'Norway',  
    'UA': 'Ukraine',  
    'UZ': 'Uzbekistan',  
    'DK': 'Denmark',  
    'AU': 'Australia',  
    'TH': 'Thailand',  
    'JM': 'Jamaica',  
    'FR': 'France',  
    'SI': 'Slovenia',  
    'BE': 'Belgium',  
    'NL': 'Netherlands',  
    'CN': 'China',  
    'LT': 'Lithuania',  
    'IT': 'Italy',  
    'NG': 'Nigeria',  
    'EE': 'Estonia',  
    'JP': 'Japan',  
    'ME': 'Montenegro',  
    'HU': 'Hungary',  
    'YU': 'Former Yugoslavia',  
    'BS': 'Bahamas',  
    'BR': 'Brazil',  
    'TZ': 'Tanzania',  
    'BN': 'Brunei',  
    'KR': 'South Korea',  
    'ZA': 'South Africa',  
    'SU': 'Former Soviet Union',  
    'HT': 'Haiti',  
    'TW': 'Taiwan',  
    'PY': 'Paraguay',  
    'VE': 'Venezuela'  
}  